# A workflow to run our check script.

name: check

on:
  pull_request:
  push:

jobs:
  run-checks:
    name: Run checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: placeholder
        run: echo Hello, world!
